### ISSUE TITLE
execute multiple calls in a single transaction

### ISSUE THREAD

**Issue by RanGojo** [Consensys/starknet-snap#181]
How is it possible to sign and send multiple calls using the snap?

It seems `starkNet_sendTransaction` function only accept one call data base on open-rpc doc.

I'm looking for something like this:

https://www.starknetjs.com/docs/API/classes/Account#execute
https://github.com/starknet-io/starknet.js/blob/1843e3c95724e801f437d9efd8d57e1ef154e743/src/account/default.ts#L275

**Comment by wantedsystem** [comment]
Hello @RanGojo we have `starkNet_executeTxn` it's on the main branch but not deployed to prod yet

**Comment by RanGojo** [comment]
@wantedsystem Cool. I'm looking forward for this feature.

**Comment by RanGojo** [comment]
@wantedsystem Hello, Do we have any update on this?

**Comment by Spunsd** [comment]
Thanks

**Comment by stanleyyconsensys** [comment]
@RanGojo the package has released and you can use it above endpoint
