### ISSUE TITLE
feat: display user stark domain in sidebar

### ISSUE THREAD

**Issue by irisdv** [Consensys/starknet-snap#183]
This feature will allow users to see their main domain instead of their hex address. 

![Capture d’écran 2023-11-30 à 14 48 46](https://github.com/Consensys/starknet-snap/assets/8224462/ddfe3896-1d5e-4d34-9c99-01d6fb93dc56)

**Implementation proposal**

To retrieve the stark name from the user address, we can call the function `address_to_domain` from the starknet ID [naming contract](https://starkscan.co/contract/0x6ac597f8116f886fa1c97a23fa4e08299975ecaf6b598873ca6792b9bbfb678#read-write-contract). This function returns an array of felt that need to be decoded to be readable. You can find more information on our encoding and decoding algorithm [here](https://docs.starknet.id/architecture/naming/encoding). 

```
callContract({
    contractAddress: namingContract,
    entrypoint: 'address_to_domain',
    calldata: [address]
});
```

[Source code](https://github.com/starknet-id/naming/blob/master/src/naming/main.cairo#L208)

**In starknet-snap:**

- Create a new method in [Starknet MetaMask Snap API](https://github.com/Consensys/starknet-snap/blob/main/packages/starknet-snap/openrpc/starknet_snap_api_openrpc.json) : `starkNet_getStarkName` 
- In [starknet-snap/src](https://github.com/Consensys/starknet-snap/tree/main/packages/starknet-snap/src) create a `getStarkName` function 

```ts
export async function getStarkName(params: ApiParams) {
  try {
    const { state, requestParams } = params;
    const requestParamsObj = requestParams as GetStarkNameRequestParam;

    // validate requestParamsObj.address argument
    // get network

    // Call a util function to get the stark domain
    const name = await getStarkNameUtil(network, requestParamsObj.address);
    logger.log(`getStarkName: name:\n${toJson(name)}`);

    return name;
  } catch (err) {
    logger.error(`Problem found: ${err}`);
    throw err;
  }
}
```
- In `starknetUtils.ts,` create a util function `getStarkName` that will use the [starknet.js](https://github.com/starknet-io/starknet.js/blob/develop/src/provider/starknetId.ts#L6) function `getStarkName` which already implement calling the starknet ID naming contract and decoding stark domain.

```ts
export const getStarkName = async (
  network: Network,
  address: string,
): Promise<string> => {
  const provider = getProvider(network);
  return provider.getStarkName(address)
};
```

**In wallet-ui**

- In [useStarkNetSnap.ts](https://github.com/Consensys/starknet-snap/blob/main/packages/wallet-ui/src/services/useStarkNetSnap.ts), add a call to our function `starkNet_getStarkName`
- Then we can use it in the [SideBar](https://github.com/Consensys/starknet-snap/blob/main/packages/wallet-ui/src/components/ui/organism/SideBar/SideBar.view.tsx) component
- update [AccountAddress.view.tsx](https://github.com/Consensys/starknet-snap/blob/main/packages/wallet-ui/src/components/ui/molecule/AccountAddress/AccountAddress.view.tsx) to have a new variable `name`

```ts
interface Props {
  address: string;
  full?: boolean;
  placement?: PopperPlacementType;
  // new variable 
  name?: string
}
```

- if `name` is defined then show `name` instead of `address`. It would require to create a `shortenName` function to shorten the name if it is too long to fit in the UI. 

If a significant number of contributors agree with our approach I'll start working on Pull Request.

Please feel free to answer on this issue and tell me what you think !

**Comment by Spunsd** [comment]
Hello

**Comment by Spunsd** [comment]
Bitcode
