### ISSUE TITLE
feat: allow users to transfer money to a .stark name

### ISSUE THREAD

**Issue by irisdv** [Consensys/starknet-snap#185]
This feature will add support to sending money to a .stark domain within the app. Here is what it could look like:

![Capture d’écran 2023-11-30 à 15 25 16](https://github.com/Consensys/starknet-snap/assets/8224462/c4b5a0a1-153c-4ede-94f1-ddd3a2645c8e)

**Implementation proposal**

To retrieve the address from the user stark name, we can call the function `domain_to_address` from the starknet ID [naming contract](https://starkscan.co/contract/0x6ac597f8116f886fa1c97a23fa4e08299975ecaf6b598873ca6792b9bbfb678#read-write-contract). This function takes in argument an encoded domain as a felt array and returns the a Starknet address. You can find more information on our encoding and decoding algorithm [here](https://docs.starknet.id/architecture/naming/encoding).

This feature will follow a similar implementation than #184. 

In starknet-snap : 
- Create a new method in [Starknet MetaMask Snap API](https://github.com/Consensys/starknet-snap/blob/main/packages/starknet-snap/openrpc/starknet_snap_api_openrpc.json) : `starkNet_getAddrFromStarkName`

In wallet-ui : 
- add a call to `starkNet_getAddrFromStarkName` and use it [SendModal](https://github.com/Consensys/starknet-snap/blob/main/packages/wallet-ui/src/components/ui/organism/Header/SendModal/SendModal.view.tsx) component
- update the `AddressInput` component and the `handleChange` function to also accept a Stark name 

If a significant number of contributors agree with our approach I'll start working on Pull Request.

Please feel free to answer on this issue and tell me what you think !

**Comment by cpp-phoenix** [comment]
Hey @irisdv, I can work on it

**Comment by Spunsd** [comment]
Blockchain

**Comment by irisdv** [comment]
> if the name not found, we should block it from the UI (the snap should already implemented a logic to block the txn)

Ok will do ! I'd like to finish this issue, but I would need version of starknet.js above 6.3.0 so the `getAddressFromStarkname` function works with the latest version of our contracts. I saw you have a draft PR ongoing to update starknet.js, can I base mine on this PR, or is it subject to change ?

**Comment by stanleyyconsensys** [comment]
The PR that upgrading the starknet.js to latest version, which is because of supporting TXN v3, however, we discover some bugs in starknet.js, and we resolved by local patching

the PR is there https://github.com/Consensys/starknet-snap/issues/185

Yes, you can base on this PR, but we may not merge that soon, we have to merge the cairo contract upgrade first, i would suggest you to wait until the cairo contract upgrade merged, as it has some breaking change on UI too

**Comment by irisdv** [comment]
I saw that #219 upgrading starknet.js was merged. Was the cairo contract upgrade PR also merged ?

**Comment by stanleyyconsensys** [comment]
No, the cairo contract PR has to re do some work due to library update

**Comment by khanti42** [comment]
Hi @irisdv , the Cairo contract PR has been merged to main. What is the status with this ?

**Comment by irisdv** [comment]
Ah great, then I'll update the PR I prepared and I'll make a PR this week on the repo if that's ok with you ?
