### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by anatsrii** [Consensys/starknet-snap#190]
Failed to fetch snap "npm:@consensys/starknet-snap": No matching versions of the snap are on the allowlist.
<img width="359" alt="Screenshot 2567-01-08 at 10 52 48" src="https://github.com/Consensys/starknet-snap/assets/85342298/aedd939a-2bec-4f0c-a11b-efb9af069288">

**Comment by anatsrii** [comment]
Can't Using MetaMask as a Starknet wallet.
Ref: https://www.starknet.io/en/posts/stark-math/getting-started-using-starknet-setting-up-a-starknet-wallet

**Comment by Spunsd** [comment]
Thank you
