### ISSUE TITLE
Bug: The snap is not on the allowlist.

### ISSUE THREAD

**Issue by mhrynenko** [Consensys/starknet-snap#266]
Trying to connect metamask snap and receive error:
```
Cannot install version "2.8.0" of snap "npm:@consensys/starknet-snap": The snap is not on the allowlist.
```
As I understood the issue that the 2.8.0 was relised, but Metamask still downloads 2.7.0 (2nd photo). 
Could this issue be fixed?

<img width="350" alt="зображення" src="https://github.com/Consensys/starknet-snap/assets/108219165/3d61337e-d50c-4678-b282-c6570a490ed3">

<img width="348" alt="зображення" src="https://github.com/Consensys/starknet-snap/assets/108219165/b2ba972c-480f-4e66-b661-a76d61b939a2">

**Comment by khanti42** [comment]
Update of the snaps-registry has been [merged](https://github.com/MetaMask/snaps-registry/pull/684)
