### ISSUE TITLE
Fix : Make `MetaMaskSnapWallet` Integration in `get-starknet` as Minimalist as Possible

### ISSUE THREAD

**Issue by khanti42** [Consensys/starknet-snap#268]
The current integration of `MetaMaskSnapWallet` in the `get-starknet` repository is not as minimalist as desired. This leads to unnecessary complexity and potential difficulties in maintaining and interacting with the `starknet/get-starknet` repo. The goal is to streamline the integration to make it as minimalist as possible.

This is linked to this [PR](https://github.com/starknet-io/get-starknet/pull/244) on `get-starknet` repo.

**Comment by stanleyyconsensys** [comment]
the target PR has merged, hence we can close the issue
