### ISSUE TITLE
Upgrade to starknet.js v 6.11.0

### ISSUE THREAD

**Issue by irisdv** [Consensys/starknet-snap#277]
Currently the starknet-snap is using version `6.7.0` of starknet.js. In order to complete #185 we need at least version `6.10.0` as we updated the starknet ID contracts on sepolia and this change was included in `6.10.0`.
Version `6.11.0` is the latest stable version of starknet.js

**Comment by stanleyyconsensys** [comment]
@irisdv we have already upgrade the version to 6.11.0, may i ask if #185 will require any update on snap rpc? if yes , you wanna need to follow the new revamp structure, we will guide you soon
