### ISSUE TITLE
Multi-Wallet Discovery and Updates to MetaMask Detection Logic

### ISSUE THREAD

**Issue by khanti42** [Consensys/starknet-snap#286]
# Description 

Multi wallet discovery is necessary because other Ethereum wallets support StarkNet and enter in conflict. To address this, updates are needed for the MetaMask detection logic and the removal of legacy MetaMask Flask support.

# Proposed changes 

Updates to the MetaMask detection logic and the removal of legacy MetaMask Flask support:

1. **Updates to `useHasMetamask.ts`:**
   - Added import for `EIP6963ProviderDetail` and `eip6963RequestProvider` from `@metamask/providers`.
   - Updated the `useEffect` hook to use the new detection method (`eip6963RequestProvider`) for checking if MetaMask is installed.
   - Modified `detectMetamask` to return a `Promise<EIP6963ProviderDetail | null>` using the new detection method.
   - Added a fallback to the legacy detection method (`detectMetamaskLegacy`) to ensure compatibility.
   - Replaced the previous `detectMetamask` function with `detectMetamaskLegacy` to handle the legacy detection process.
   - Cleaned up the `getProvider` function by removing commented lines and refining provider detection logic.

2. **Removal of `useHasMetamaskFlask.ts`:**
   - Deleted the file `useHasMetamaskFlask.ts`, which contained logic for detecting MetaMask Flask. This removal indicates that Flask-specific logic is no longer necessary due to updates in MetaMask's support for Snaps.

# Impact 

These changes are necessary to support multi-wallet discovery and to prevent conflicts with other Ethereum wallets that support StarkNet. The updates streamline the MetaMask detection process and remove outdated logic related to MetaMask Flask.

**Comment by vivek-consensys** [comment]
User able to connect to MM whilst having OKX wallet as an extension. 
![image](https://github.com/user-attachments/assets/99439891-762f-4ac3-9233-f9c22fb15352)
